)name: Java CI with Gradle

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 配置 Gradle 缓存以加速构建
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
      with:
        # 如果使用特定 Gradle 版本，可以取消注释下面这行
          gradle-version: '8.8'
        
    # 授予 Gradle Wrapper 执行权限（Linux 系统需要）
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # 构建模组 - 添加必要的参数
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      env:
        # 设置内存限制以防止 OOM
        GRADLE_OPTS: -Xmx2g -Dorg.gradle.daemon=false
        
    # 可选：上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: forge-mod-build
        path: build/libs/
        retention-days: 5
        compress-level: 0
